import os
import re
import json
import arxiv
import yaml
import logging
import argparse
import datetime
import requests

logging.basicConfig(format='[%(asctime)s %(levelname)s] %(message)s',
                    datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

github_url = "https://api.github.com/search/repositories"
arxiv_url = "http://arxiv.org/"

def load_config(config_file:str) -> dict:
    '''
    config_file: input config file path
    return: a dict of configuration
    '''
    # make filters pretty
    def pretty_filters(**config) -> dict:
        keywords = dict()
        EXCAPE = '\"'
        QUOTA = '' # NO-USE
        OR = ' OR ' # TODO
        def parse_filters(filters:list):
            ret = ''
            for idx in range(0,len(filters)):
                filter = filters[idx]
                if len(filter.split()) > 1:
                    ret += (EXCAPE + filter + EXCAPE)
                else:
                    ret += (QUOTA + filter + QUOTA)
                if idx != len(filters) - 1:
                    ret += OR
            return ret
        for k,v in config['keywords'].items():
            keywords[k] = parse_filters(v['filters'])
        return keywords
    with open(config_file,'r') as f:
        config = yaml.load(f,Loader=yaml.FullLoader)
        config['kv'] = pretty_filters(**config)
        
        # 读取领域筛选关键词
        if 'domain_filters' in config:
            config['domain_filters'] = config['domain_filters']
        else:
            config['domain_filters'] = {}
        
        logging.info(f'config = {config}')
    return config

def get_authors(authors, first_author = False):
    output = str()
    if first_author == False:
        output = ", ".join(str(author) for author in authors)
    else:
        output = authors[0]
    return output
def sort_papers(papers):
    output = dict()
    keys = list(papers.keys())
    keys.sort(reverse=True)
    for key in keys:
        output[key] = papers[key]
    return output
import requests

def get_code_link(qword:str) -> str:
    """
    This short function was auto-generated by ChatGPT.
    I only renamed some params and added some comments.
    @param qword: query string, eg. arxiv ids and paper titles
    @return paper_code in github: string, if not found, return None
    """
    # query = f"arxiv:{arxiv_id}"
    query = f"{qword}"
    params = {
        "q": query,
        "sort": "stars",
        "order": "desc"
    }
    r = requests.get(github_url, params=params)
    results = r.json()
    code_link = None
    if results["total_count"] > 0:
        code_link = results["items"][0]["html_url"]
    return code_link

def filter_papers_by_domain(papers_data, domain_filters):
    '''
    对论文进行二次筛选，只保留自动驾驶或机器人相关的论文
    @param papers_data: 字典格式的论文数据 {paper_id: paper_content}
    @param domain_filters: 领域筛选关键词列表
    @return: 筛选后的论文数据
    '''
    filtered_papers = {}
    
    for paper_id, paper_content in papers_data.items():
        # 从论文内容中提取标题和摘要信息
        # paper_content格式: "|**{date}**|**{title}**|{authors}|[{arxiv_id}]({url})|{code}|"
        parts = paper_content.split('|')
        if len(parts) >= 3:
            title = parts[2].strip().replace('**', '').replace('**', '')
            
            # 检查标题是否包含任何领域关键词
            match_found = False
            for keyword in domain_filters:
                if keyword.lower() in title.lower():
                    match_found = True
                    break
            
            # 如果标题匹配，保留该论文
            if match_found:
                filtered_papers[paper_id] = paper_content
            else:
                logging.info(f"Filtered out paper: {title} (no domain keyword match)")
    
    return filtered_papers

def get_daily_papers(topic, query="slam", max_results=2, domain_filters=None, final_max_results=None):
    """
    @param topic: str
    @param query: str
    @param domain_filters: list, 领域筛选关键词列表
    @param final_max_results: int, 最终要筛选的论文数量，如果为None则使用max_results
    @return paper_with_code: dict
    """
    # 如果没有指定最终目标数量，则使用max_results
    if final_max_results is None:
        final_max_results = max_results
    
    # output
    content = dict()
    content_to_web = dict()
    
    # 如果启用了领域筛选，使用循环持续获取直到达到目标数量
    if domain_filters:
        batch_size = 20  # 每次获取的论文数量
        max_iterations = 10  # 最大循环次数，防止无限循环
        total_fetched = 0  # 记录已获取的总论文数
        
        logging.info(f"Domain filtering enabled, target: {final_max_results} papers, batch size: {batch_size}")
        
        for iteration in range(max_iterations):
            if len(content) >= final_max_results:
                logging.info(f"Reached target of {final_max_results} papers, stopping search")
                break
            
            start_index = total_fetched
            end_index = start_index + batch_size
            
            logging.info(f"Iteration {iteration + 1}/{max_iterations}: fetching papers {start_index}-{end_index}")
            
            search_engine = arxiv.Search(
                query = query,
                max_results = end_index,
                sort_by = arxiv.SortCriterion.SubmittedDate
            )
            
            # 获取结果并跳过之前已经处理过的论文
            results = list(search_engine.results())
            results = results[start_index:]  # 只处理新获取的论文
            
            if not results:
                logging.info("No more papers available, stopping search")
                break
            
            matched_count = len(content)  # 记录当前匹配的论文数量
            new_papers_found = False
            
            for result in results:
                paper_id            = result.get_short_id()
                paper_title         = result.title
                paper_url           = result.entry_id
                paper_abstract      = result.summary.replace("\\n"," ")
                paper_authors       = get_authors(result.authors)
                paper_first_author  = get_authors(result.authors,first_author = True)
                primary_category    = result.primary_category
                publish_time        = result.published.date()
                update_time         = result.updated.date()
                comments            = result.comment

                logging.info(f"Time = {update_time} title = {paper_title} author = {paper_first_author}")

                # 二次筛选：检查论文标题是否包含领域关键词
                domain_match = False
                for keyword in domain_filters:
                    if keyword.lower() in paper_title.lower():
                        domain_match = True
                        break
                
                if not domain_match:
                    logging.info(f"Filtered out paper: {paper_title} (no domain keyword match)")
                    continue  # 跳过不匹配的论文
                
                new_papers_found = True
                
                # eg: 2108.09112v1 -> 2108.09112
                ver_pos = paper_id.find('v')
                if ver_pos == -1:
                    paper_key = paper_id
                else:
                    paper_key = paper_id[0:ver_pos]
                paper_url = arxiv_url + 'abs/' + paper_key

                # Since PapersWithCode API is deprecated, we no longer fetch code links
                # Papers will be listed without code links
                content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|null|\n".format(
                       update_time,paper_title,paper_first_author,paper_key,paper_url)
                content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({})".format(
                       update_time,paper_title,paper_first_author,paper_url,paper_url)

                # TODO: select useful comments
                comments = None
                if comments != None:
                    content_to_web[paper_key] += f", {comments}\n"
                else:
                    content_to_web[paper_key] += f"\n"

                # 如果已经达到目标数量，停止处理当前批次
                if len(content) >= final_max_results:
                    logging.info(f"Reached target of {final_max_results} papers, stopping")
                    break
            
            total_fetched = end_index
            
            # 如果这批次没有找到任何新论文，说明已经没有更多相关论文了
            if not new_papers_found:
                logging.info(f"No matching papers found in iteration {iteration + 1}, stopping search")
                break
            
            matched_count = len(content) - matched_count
            logging.info(f"Iteration {iteration + 1} found {matched_count} matching papers, total: {len(content)}/{final_max_results}")
        
        logging.info(f"Domain filtering complete: found {len(content)} papers matching domain criteria (target: {final_max_results})")
    else:
        # 不启用领域筛选时，直接获取指定数量的论文
        search_engine = arxiv.Search(
            query = query,
            max_results = max_results,
            sort_by = arxiv.SortCriterion.SubmittedDate
        )

        for result in search_engine.results():

            paper_id            = result.get_short_id()
            paper_title         = result.title
            paper_url           = result.entry_id
            paper_abstract      = result.summary.replace("\\n"," ")
            paper_authors       = get_authors(result.authors)
            paper_first_author  = get_authors(result.authors,first_author = True)
            primary_category    = result.primary_category
            publish_time        = result.published.date()
            update_time         = result.updated.date()
            comments            = result.comment

            logging.info(f"Time = {update_time} title = {paper_title} author = {paper_first_author}")

            # eg: 2108.09112v1 -> 2108.09112
            ver_pos = paper_id.find('v')
            if ver_pos == -1:
                paper_key = paper_id
            else:
                paper_key = paper_id[0:ver_pos]
            paper_url = arxiv_url + 'abs/' + paper_key

            # Since PapersWithCode API is deprecated, we no longer fetch code links
            # Papers will be listed without code links
            content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|null|\n".format(
                   update_time,paper_title,paper_first_author,paper_key,paper_url)
            content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({})".format(
                   update_time,paper_title,paper_first_author,paper_url,paper_url)

            # TODO: select useful comments
            comments = None
            if comments != None:
                content_to_web[paper_key] += f", {comments}\n"
            else:
                content_to_web[paper_key] += f"\n"
        
        logging.info(f"Found {len(content)} papers (no domain filtering)")

    data = {topic:content}
    data_web = {topic:content_to_web}
    
    return data,data_web

def update_paper_links(filename):
    '''
    weekly update paper links in json file
    '''
    def parse_arxiv_string(s):
        parts = s.split("|")
        date = parts[1].strip()
        title = parts[2].strip()
        authors = parts[3].strip()
        arxiv_id = parts[4].strip()
        code = parts[5].strip()
        arxiv_id = re.sub(r'v\d+', '', arxiv_id)
        return date,title,authors,arxiv_id,code

    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)

        json_data = m.copy()

        for keywords,v in json_data.items():
            logging.info(f'keywords = {keywords}')
            for paper_id,contents in v.items():
                contents = str(contents)

                update_time, paper_title, paper_first_author, paper_url, code_url = parse_arxiv_string(contents)

                contents = "|{}|{}|{}|{}|{}|\n".format(update_time,paper_title,paper_first_author,paper_url,code_url)
                json_data[keywords][paper_id] = str(contents)
                logging.info(f'paper_id = {paper_id}, contents = {contents}')

                # PapersWithCode API is deprecated, skip code link updates
                # Papers will keep their existing null code links
                logging.info(f'Skipping code link update for paper_id = {paper_id} (PapersWithCode API deprecated)')
        # dump to json file
        with open(filename,"w") as f:
            json.dump(json_data,f)

def update_json_file(filename,data_dict):
    '''
    daily update json file using data_dict
    '''
    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)

    json_data = m.copy()

    # update papers in each keywords
    for data in data_dict:
        for keyword in data.keys():
            papers = data[keyword]

            if keyword in json_data.keys():
                json_data[keyword].update(papers)
            else:
                json_data[keyword] = papers

    with open(filename,"w") as f:
        json.dump(json_data,f)

def json_to_md(filename,md_filename,
               task = '',
               to_web = False,
               use_title = True,
               use_tc = True,
               show_badge = True,
               use_b2t = True):
    """
    @param filename: str
    @param md_filename: str
    @return None
    """
    def pretty_math(s:str) -> str:
        ret = ''
        match = re.search(r"\$.*\$", s)
        if match == None:
            return s
        math_start,math_end = match.span()
        space_trail = space_leading = ''
        if s[:math_start][-1] != ' ' and '*' != s[:math_start][-1]: space_trail = ' '
        if s[math_end:][0] != ' ' and '*' != s[math_end:][0]: space_leading = ' '
        ret += s[:math_start]
        ret += f'{space_trail}${match.group()[1:-1].strip()}${space_leading}'
        ret += s[math_end:]
        return ret

    DateNow = datetime.date.today()
    DateNow = str(DateNow)
    DateNow = DateNow.replace('-','.')

    with open(filename,"r") as f:
        content = f.read()
        if not content:
            data = {}
        else:
            data = json.loads(content)

    # clean README.md if daily already exist else create it
    with open(md_filename,"w+") as f:
        pass

    # write data into README.md
    with open(md_filename,"a+") as f:

        if (use_title == True) and (to_web == True):
            f.write("---\n" + "layout: default\n" + "---\n\n")

        # if show_badge == True:
        #     f.write(f"[![Contributors][contributors-shield]][contributors-url]\n")
        #     f.write(f"[![Forks][forks-shield]][forks-url]\n")
        #     f.write(f"[![Stargazers][stars-shield]][stars-url]\n")
        #     f.write(f"[![Issues][issues-shield]][issues-url]\n\n")

        if use_title == True:
            #f.write(("<p align="center"><h1 align="center"><br><ins>CV-ARXIV-DAILY"
            #         "</ins><br>Automatically Update CV Papers Daily</h1></p>\n"))
            f.write("## Updated on " + DateNow + "\n")
        else:
            f.write("> Updated on " + DateNow + "\n")

        # TODO: add usage
        f.write("> Usage instructions: [here](./docs/README.md#usage)\n\n")

        #Add: table of contents
        if use_tc == True:
            f.write("<details>\n")
            f.write("  <summary>Table of Contents</summary>\n")
            f.write("  <ol>\n")
            for keyword in data.keys():
                day_content = data[keyword]
                if not day_content:
                    continue
                kw = keyword.replace(' ','-')
                f.write(f"    <li><a href=#{kw.lower()}>{keyword}</a></li>\n")
            f.write("  </ol>\n")
            f.write("</details>\n\n")

        for keyword in data.keys():
            day_content = data[keyword]
            if not day_content:
                continue
            # the head of each part
            f.write(f"## {keyword}\n\n")

            if use_title == True :
                if to_web == False:
                    f.write("|Publish Date|Title|Authors|PDF|Code|\n" + "|---|---|---|---|---|\n")
                else:
                    f.write("| Publish Date | Title | Authors | PDF | Code |\n")
                    f.write("|:---------|:-----------------------|:---------|:------|:------|\n")

            # sort papers by date
            day_content = sort_papers(day_content)

            for _,v in day_content.items():
                if v is not None:
                    f.write(pretty_math(v)) # make latex pretty

            f.write(f"\n")

            #Add: back to top
            if use_b2t:
                top_info = f"#Updated on {DateNow}"
                top_info = top_info.replace(' ','-').replace('.','')
                f.write(f"<p align=right>(<a href={top_info.lower()}>back to top</a>)</p>\n\n")

        if show_badge == True:
            # we don't like long string, break it!
            # Modified by HuJiaming11: Updated GitHub username from Vincentqyw to HuJiaming11
            f.write((f"[contributors-shield]: https://img.shields.io/github/"
                     f"contributors/HuJiaming11/rl-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[contributors-url]: https://github.com/HuJiaming11/"
                     f"rl-arxiv-daily/graphs/contributors\n"))
            f.write((f"[forks-shield]: https://img.shields.io/github/forks/HuJiaming11/"
                     f"rl-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[forks-url]: https://github.com/HuJiaming11/"
                     f"rl-arxiv-daily/network/members\n"))
            f.write((f"[stars-shield]: https://img.shields.io/github/stars/HuJiaming11/"
                     f"rl-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[stars-url]: https://github.com/HuJiaming11/"
                     f"rl-arxiv-daily/stargazers\n"))
            f.write((f"[issues-shield]: https://img.shields.io/github/issues/HuJiaming11/"
                     f"rl-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[issues-url]: https://github.com/HuJiaming11/"
                     f"rl-arxiv-daily/issues\n\n"))

    logging.info(f"{task} finished")

def demo(**config):
    # TODO: use config
    data_collector = []
    data_collector_web= []

    keywords = config['kv']
    max_results = config['max_results']
    # 获取最终要筛选的论文数量，如果配置中没有则使用max_results
    final_max_results = config.get('final_max_results', max_results)
    publish_readme = config['publish_readme']
    publish_gitpage = config['publish_gitpage']
    publish_wechat = config['publish_wechat']
    show_badge = config['show_badge']

    # 🔍 获取领域筛选关键词
    domain_filters = []
    if 'domain_filters' in config:
        for domain, filters in config['domain_filters'].items():
            domain_filters.extend(filters)
    
    if domain_filters:
        logging.info(f"Domain filtering enabled with keywords: {domain_filters}")
        logging.info(f"Final target papers: {final_max_results}")
    else:
        logging.info("No domain filtering enabled")

    b_update = config['update_paper_links']
    logging.info(f'Update Paper Link = {b_update}')
    if config['update_paper_links'] == False:
        logging.info(f"GET daily papers begin")
        for topic, keyword in keywords.items():
            logging.info(f"Keyword: {topic}")
            data, data_web = get_daily_papers(
                topic, 
                query = keyword,
                max_results = max_results,
                domain_filters = domain_filters,  # 🔍 传递领域筛选关键词
                final_max_results = final_max_results  # 🔍 传递最终目标论文数量
            )
            data_collector.append(data)
            data_collector_web.append(data_web)
            print("\n")
        logging.info(f"GET daily papers end")

    # 1. update README.md file
    if publish_readme:
        json_file = config['json_readme_path']
        md_file   = config['md_readme_path']
        # update paper links
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:
            # update json data
            update_json_file(json_file,data_collector)
        # json data to markdown
        json_to_md(json_file,md_file, task ='Update Readme', \
            show_badge = show_badge)

    # 2. update docs/index.md file (to gitpage)
    if publish_gitpage:
        json_file = config['json_gitpage_path']
        md_file   = config['md_gitpage_path']
        # TODO: duplicated update paper links!!!
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:
            update_json_file(json_file,data_collector)
        json_to_md(json_file, md_file, task ='Update GitPage', \
            to_web = True, show_badge = show_badge, \
            use_tc=False, use_b2t=False)

    # 3. Update docs/wechat.md file
    if publish_wechat:
        json_file = config['json_wechat_path']
        md_file   = config['md_wechat_path']
        # TODO: duplicated update paper links!!!
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:
            update_json_file(json_file, data_collector_web)
        json_to_md(json_file, md_file, task ='Update Wechat', \
            to_web=False, use_title= False, show_badge = show_badge)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config_path',type=str, default='config.yaml',
                            help='configuration file path')
    parser.add_argument('--update_paper_links', default=False,
                        action="store_true",help='whether to update paper links etc.')
    args = parser.parse_args()
    config = load_config(args.config_path)
    config = {**config, 'update_paper_links':args.update_paper_links}
    demo(**config)
